specVersion: 1.0.0
name: moonbeam-evm
version: 0.1.0
runner:
  node:
    name: '@subql/node'
    version: '>=1.0.0'
  query:
    name: '@subql/query'
    version: '>=1.0.0'
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  chainId: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527'
  endpoint: 'wss://moonbeam-alpha.api.onfinality.io/public-ws'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    processor:
      file: ./node_modules/@subql/frontier-evm-processor/dist/bundle.js
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
