specVersion: 1.0.0
name: SubQuery Dictionary - Polkadot
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '>=2.0.0'
  query:
    name: '@subql/query'
    version: '>=1.11.2'
description: >-
  A SubQuery Dictionary Project that provides increased indexing speed to all projects
repository: 'https://github.com/subquery/dictionary-projects/dictionaries/polkadot'
schema:
  file: ./schema.graphql
network:
  chainId: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  endpoint: 'wss://polkadot.api.onfinality.io/public-ws'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
