specVersion: 0.2.0
name: SubQuery Dictionary - Parallel Finance
version: 1.0.0
description: >-
  A SubQuery Dictionary Project that provides increased indexing speed to all projects
repository: https://github.com/subquery/subql-dictionary
schema:
  file: ./schema.graphql
network:
  genesisHash: "0xe61a41c53f5dcd0beb09df93b34402aada44cb05117b71059cce40a2723a4e97"
  endpoint: wss://parallel.api.onfinality.io/public-ws
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
