specVersion: 0.2.0
name: SubQuery Dictionary - Parallel Heiko
version: 1.0.0
description: "A SubQuery Dictionary Project that provides increased indexing speed to all projects"
repository: https://github.com/subquery/subql-dictionary
schema:
  file: ./schema.graphql
network:
  genesisHash: "0x64a1c658a48b2e70a7fb1ad4c39eea35022568c20fc44a6e2e3d0a57aee6053b"
  endpoint: wss://parallel-heiko.api.onfinality.io/public-ws
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
