specVersion: 0.2.0
name: SubQuery Dictionary - Basilisk
version: 1.0.0
description: "A SubQuery Dictionary Project that provides increased indexing speed to all projects"
repository: https://github.com/subquery/subql-dictionary
schema:
  file: ./schema.graphql
network:
  genesisHash: "0xa85cfb9b9fd4d622a5b28289a02347af987d8f73fa3108450e2b4a11c1ce5755"
  endpoint: wss://basilisk.api.onfinality.io/public-ws
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
