specVersion: 1.0.0
name: SubQuery Dictionary - Astar
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '>=0.32.0'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  A SubQuery Dictionary Project that provides increased indexing speed to all
  projects
repository: 'https://github.com/subquery/subql-dictionary'
schema:
  file: ./schema.graphql
network:
  chainId: '0xddb89973361a170839f80f152d2e9e38a376a5a7eccefcade763f46a8e567019'
  endpoint: 'wss://public-rpc.pinknode.io/shibuya'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
