specVersion: 0.2.0
name: SubQuery Dictionary - ContextFree Network
version: 1.0.0
description: "A SubQuery Dictionary Project that provides increased indexing speed to all projects"
repository: https://github.com/subquery/subql-dictionary
schema:
  file: ./schema.graphql
network:
  genesisHash: "0x6254c948b5eb7199a112cb308be3385c39c8c942625540ac749c77fe2aebc299"
  endpoint: wss://contextfree.api.onfinality.io/public-ws
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
