specVersion: 1.0.0
name: SubQuery Dictionary - Calamari
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  A SubQuery Dictionary Project that provides increased indexing speed to all
  projects
repository: 'https://github.com/subquery/subql-dictionary'
schema:
  file: ./schema.graphql
network:
  chainId: '0x4ac80c99289841dd946ef92765bf659a307d39189b3ce374a92b5f0415ee17a1'
  endpoint: 'wss://ws.calamari.systems/'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
