specVersion: 0.2.0
name: SubQuery Dictionary - Moonbase Alpha
version: 1.0.0
description: "A SubQuery Dictionary Project that provides increased indexing speed to all projects"
repository: https://github.com/subquery/subql-dictionary
schema:
  file: ./schema.graphql
network:
  genesisHash: "0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527"
  endpoint: wss://moonbeam-alpha.api.onfinality.io/public-ws
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
